language: node_js
sudo: false
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'node'
before_script:
  - npm prune
script:
  - yarn run build
  - yarn run test -- --coverage
after_success:
  - yarn run report-coverage
  - NPM_TOKEN=${NPM_TOKEN} GH_TOKEN=${GH_TOKEN} yarn run release
